version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - ./storage:/app/storage
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped